'use client';

import { useEffect, useState } from 'react';
import { exportReports, getReportMetrics, operationsApiMessage } from '@/lib/operations-api';
import type { OperationsFilters, ReportMetrics } from '@/lib/operations-types';
import { EmptyState, ErrorState, LoadingState } from './ui';

const cards: { key: keyof ReportMetrics; label: string }[] = [{ key: 'mttr', label: 'MTTR' }, { key: 'mtbf', label: 'MTBF' }, { key: 'totalDowntime', label: 'Total Downtime' }, { key: 'responseTime', label: 'Response Time' }, { key: 'slaCompliance', label: 'SLA Compliance' }, { key: 'ticketVolume', label: 'Ticket Volume' }, { key: 'repeatFailures', label: 'Repeat Failures' }];
function metricValue(value: ReportMetrics[keyof ReportMetrics]) { return Array.isArray(value) ? '--' : value ?? '--'; }
export function ReportsDashboard() {
  const [filters, setFilters] = useState<OperationsFilters>({}); const [metrics, setMetrics] = useState<ReportMetrics | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [exporting, setExporting] = useState(false);
  useEffect(() => { let active = true; setLoading(true); getReportMetrics(filters).then((data) => { if (active) setMetrics(data); }).catch((reason) => { if (active) setError(operationsApiMessage(reason)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [filters]);
  async function exportReport() { setExporting(true); setError(''); try { const blob = await exportReports(filters); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'maintenance-report.csv'; link.click(); URL.revokeObjectURL(url); } catch (reason) { setError(operationsApiMessage(reason)); } finally { setExporting(false); } }
  return <div className="reports-dashboard"><div className="report-controls"><label>Plant<input value={filters.plant ?? ''} onChange={(event) => setFilters({ ...filters, plant: event.target.value })} placeholder="All plants" /></label><label>Date<input type="date" value={filters.date ?? ''} onChange={(event) => setFilters({ ...filters, date: event.target.value })} /></label><button className="secondary-action" onClick={exportReport} disabled={exporting}>{exporting ? 'Preparing...' : 'Export report'}</button></div>{loading ? <LoadingState label="Loading report metrics" /> : error ? <ErrorState title="Reports unavailable" description={error} /> : metrics && Object.keys(metrics).length ? <><div className="report-metric-grid">{cards.map((card) => <article className="metric-card" key={card.key}><span className="metric-card__label">{card.label}</span><strong className="metric-card__value">{metricValue(metrics[card.key])}</strong><span className="metric-card__status">Laravel source</span></article>)}</div><div className="report-tables"><ReportTable title="Maintenance by Plant" rows={metrics.maintenanceByPlant?.map((item) => [item.plant, String(item.total)]) ?? []} /><ReportTable title="Top Problematic Machines" rows={metrics.topProblematicMachines?.map((item) => [item.machine, String(item.total)]) ?? []} /><ReportTable title="Top Failure Types" rows={metrics.topFailureTypes?.map((item) => [item.type, String(item.total)]) ?? []} /></div></> : <EmptyState title="No report data" description="No metrics are available for the selected filters." />}</div>;
}
function ReportTable({ title, rows }: { title: string; rows: string[][] }) { return <section className="work-panel report-table"><div className="work-panel__header"><h3>{title}</h3><span>API DATA</span></div>{rows.length ? rows.map((row) => <div className="report-row" key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong></div>) : <EmptyState title="No data" description="The Laravel report returned no records." />}</section>; }
