'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getSupervisorOverview, operationsApiMessage } from '@/lib/operations-api';
import type { SupervisorOverview } from '@/lib/operations-types';
import { EmptyState, ErrorState, LoadingState } from './ui';

export function SupervisorDashboard() { const [overview, setOverview] = useState<SupervisorOverview | null>(null); const [error, setError] = useState(''); useEffect(() => { getSupervisorOverview().then(setOverview).catch((reason) => setError(operationsApiMessage(reason))); }, []); if (error) return <ErrorState title="Supervisor view unavailable" description={error} />; if (!overview) return <LoadingState label="Loading supervisor view" />; return <div className="supervisor-dashboard"><div className="supervisor-grid"><Queue title="Unassigned tickets" tickets={overview.unassigned} /><Queue title="Critical tickets" tickets={overview.critical} /><Queue title="Overdue tickets" tickets={overview.overdue} /></div><section className="work-panel workload-panel"><div className="work-panel__header"><h3>Technician workload</h3><span>LIVE ASSIGNMENTS</span></div>{overview.workload.length ? <div className="workload-table">{overview.workload.map((row) => <div className="workload-row" key={row.technicianId}><strong>{row.technician}</strong><span>Assigned <b>{row.assigned}</b></span><span>In progress <b>{row.inProgress}</b></span><span>Overdue <b className={row.overdue ? 'sla-overdue' : ''}>{row.overdue}</b></span><span>Resolved <b>{row.resolved}</b></span></div>)}</div> : <EmptyState title="No workload data" description="The Laravel supervisor endpoint returned no technicians." />}</section><section className="work-panel"><div className="work-panel__header"><h3>Repeated machine failures</h3><span>ATTENTION</span></div>{overview.repeatedFailures.length ? overview.repeatedFailures.map((item) => <div className="report-row" key={item.machineId}><span>{item.machine}</span><strong>{item.count} failures</strong></div>) : <EmptyState title="No repeat failures" description="No repeated failure data is available." />}</section></div>; }
function Queue({ title, tickets }: { title: string; tickets: SupervisorOverview['overdue'] }) { return <section className="work-panel supervisor-queue"><div className="work-panel__header"><h3>{title}</h3><span>{tickets.length}</span></div>{tickets.length ? tickets.slice(0, 5).map((ticket) => <Link href={`/tickets/${ticket.id}`} className="report-row" key={ticket.id}><span><strong>{ticket.number}</strong><small>{ticket.machine}</small></span><b className={`ticket-status ticket-status--${ticket.status.toLowerCase()}`}>{ticket.status}</b></Link>) : <EmptyState title="Queue clear" description="No tickets require attention." />}</section>; }
